[package]

name = "piston2d-opengl_graphics"
version = "0.1.0"
authors = [
    "bvssvni <bvssvni@gmail.com>",
    "Coeuvre <coeuvre@gmail.com>",
    "gmorenz",
    "leonkunert <info@leonkunert.de>",
    "mitchmindtree <me@michellnordine.com>",
    "Christiandh",
    "Apointos",
    "ccgn",
    "reem",
    "TyOverby <ty@pre-alpha.com>"
]
keywords = ["opengl", "graphics", "2d", "piston"]
description = "An OpenGL 2D back-end for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/opengl_graphics.git"
homepage = "https://github.com/PistonDevelopers/opengl_graphics"

[lib]
name = "opengl_graphics"
path = "src/lib.rs"

[features]
default = ["image_png"]
image_gif = ["image/gif"]
image_jpeg = ["image/jpeg"]
image_png = ["image/png"]
image_ppm = ["image/ppm"]
image_tga = ["image/tga"]
image_tiff = ["image/tiff"]
image_webp = ["image/webp"]


[dependencies.image]
version = "0.3.10"
default-features = false

[dependencies]
freetype-rs = "0.1.0"
gl = "0.0.12"
libc = "0.1.8"
piston-shaders_graphics2d = "0.1.0"
piston-texture = "0.1.0"
shader_version = "0.1.0"

[dependencies.piston2d-graphics]
git = "https://github.com/tedajax/graphics.git"

[dev-dependencies]
piston = "0.1.4"
pistoncore-sdl2_window = "0.1.0"

[build-dependencies]
khronos_api = "0.0.5"

